# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "omniauth-diandian"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["secretworry"]
  s.date = "2012-08-01"
  s.description = "And OmniAuth Strategy for diandian using OAuth2"
  s.email = "dusiyh@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "lib/omniauth-diandian.rb",
    "lib/omniauth-diandian/version.rb",
    "lib/omniauth/strategies/diandian.rb",
    "omniauth-diandian.gemspec",
    "test/helper.rb",
    "test/test_omniauth-diandian.rb"
  ]
  s.homepage = "http://github.com/secretworry/omniauth-diandian"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "OmniAuth Strategy for diandian"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<diandian-oauth>, ["> 0"])
      s.add_runtime_dependency(%q<omniauth>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<omniauth-oauth2>, ["~> 1.1.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_runtime_dependency(%q<diandian-oauth>, ["> 0"])
      s.add_runtime_dependency(%q<omniauth>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<omniauth-oauth2>, ["~> 1.1.0"])
    else
      s.add_dependency(%q<diandian-oauth>, ["> 0"])
      s.add_dependency(%q<omniauth>, ["~> 1.1.0"])
      s.add_dependency(%q<omniauth-oauth2>, ["~> 1.1.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<diandian-oauth>, ["> 0"])
      s.add_dependency(%q<omniauth>, ["~> 1.1.0"])
      s.add_dependency(%q<omniauth-oauth2>, ["~> 1.1.0"])
    end
  else
    s.add_dependency(%q<diandian-oauth>, ["> 0"])
    s.add_dependency(%q<omniauth>, ["~> 1.1.0"])
    s.add_dependency(%q<omniauth-oauth2>, ["~> 1.1.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<diandian-oauth>, ["> 0"])
    s.add_dependency(%q<omniauth>, ["~> 1.1.0"])
    s.add_dependency(%q<omniauth-oauth2>, ["~> 1.1.0"])
  end
end

